// Code generated by gen_md5x4; DO NOT EDIT.
// 4-way MD5 ARM64 NEON — 64 unrolled steps with implicit register rotation.
// Uses only native Go ARM64 assembler mnemonics (no WORD encodings).
// VBIC/VORN emulated via VEOR(allones) + VAND/VORR.

#include "textflag.h"

// func md5x4core(x *[16][4]uint32, state *[4][4]uint32)
TEXT ·md5x4core(SB), NOSPLIT, $0-16
	MOVD x+0(FP), R0
	MOVD state+8(FP), R1

	VLD1 0(R1), [V0.S4, V1.S4, V2.S4, V3.S4]

	// Load all-ones into V8 (for VBIC/VORN emulation)
	MOVD $allones<>(SB), R2
	VLD1 (R2), [V8.S4]

	// Save initial state for final add-back
	VMOV V0.B16, V4.B16
	VMOV V1.B16, V5.B16
	VMOV V2.B16, V6.B16
	VMOV V3.B16, V7.B16

	ADD $0, R0, R4
	VLD1 (R4), [V13.S4]

	// Step 0: R1 g=0 s=7 T=0xd76aa478  (a=V0 b=V1 c=V2 d=V3)
	VAND V1.B16, V2.B16, V9.B16   // b & c
	VEOR V8.B16, V1.B16, V10.B16  // ~b
	VAND V10.B16, V3.B16, V10.B16 // ~b & d
	VORR V9.B16, V10.B16, V12.B16  // F
	VADD V0.S4, V13.S4, V14.S4   // a + X
	MOVD $T_0<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $16, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $7, V12.S4, V11.S4   // x << s
	VUSHR $25, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V1.S4, V12.S4, V0.S4

	// Step 1: R1 g=1 s=12 T=0xe8c7b756  (a=V3 b=V0 c=V1 d=V2)
	VAND V0.B16, V1.B16, V9.B16   // b & c
	VEOR V8.B16, V0.B16, V10.B16  // ~b
	VAND V10.B16, V2.B16, V10.B16 // ~b & d
	VORR V9.B16, V10.B16, V12.B16  // F
	VADD V3.S4, V13.S4, V14.S4   // a + X
	MOVD $T_1<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $32, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $12, V12.S4, V11.S4   // x << s
	VUSHR $20, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V0.S4, V12.S4, V3.S4

	// Step 2: R1 g=2 s=17 T=0x242070db  (a=V2 b=V3 c=V0 d=V1)
	VAND V3.B16, V0.B16, V9.B16   // b & c
	VEOR V8.B16, V3.B16, V10.B16  // ~b
	VAND V10.B16, V1.B16, V10.B16 // ~b & d
	VORR V9.B16, V10.B16, V12.B16  // F
	VADD V2.S4, V13.S4, V14.S4   // a + X
	MOVD $T_2<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $48, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $17, V12.S4, V11.S4   // x << s
	VUSHR $15, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V3.S4, V12.S4, V2.S4

	// Step 3: R1 g=3 s=22 T=0xc1bdceee  (a=V1 b=V2 c=V3 d=V0)
	VAND V2.B16, V3.B16, V9.B16   // b & c
	VEOR V8.B16, V2.B16, V10.B16  // ~b
	VAND V10.B16, V0.B16, V10.B16 // ~b & d
	VORR V9.B16, V10.B16, V12.B16  // F
	VADD V1.S4, V13.S4, V14.S4   // a + X
	MOVD $T_3<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $64, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $22, V12.S4, V11.S4   // x << s
	VUSHR $10, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V2.S4, V12.S4, V1.S4

	// Step 4: R1 g=4 s=7 T=0xf57c0faf  (a=V0 b=V1 c=V2 d=V3)
	VAND V1.B16, V2.B16, V9.B16   // b & c
	VEOR V8.B16, V1.B16, V10.B16  // ~b
	VAND V10.B16, V3.B16, V10.B16 // ~b & d
	VORR V9.B16, V10.B16, V12.B16  // F
	VADD V0.S4, V13.S4, V14.S4   // a + X
	MOVD $T_4<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $80, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $7, V12.S4, V11.S4   // x << s
	VUSHR $25, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V1.S4, V12.S4, V0.S4

	// Step 5: R1 g=5 s=12 T=0x4787c62a  (a=V3 b=V0 c=V1 d=V2)
	VAND V0.B16, V1.B16, V9.B16   // b & c
	VEOR V8.B16, V0.B16, V10.B16  // ~b
	VAND V10.B16, V2.B16, V10.B16 // ~b & d
	VORR V9.B16, V10.B16, V12.B16  // F
	VADD V3.S4, V13.S4, V14.S4   // a + X
	MOVD $T_5<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $96, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $12, V12.S4, V11.S4   // x << s
	VUSHR $20, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V0.S4, V12.S4, V3.S4

	// Step 6: R1 g=6 s=17 T=0xa8304613  (a=V2 b=V3 c=V0 d=V1)
	VAND V3.B16, V0.B16, V9.B16   // b & c
	VEOR V8.B16, V3.B16, V10.B16  // ~b
	VAND V10.B16, V1.B16, V10.B16 // ~b & d
	VORR V9.B16, V10.B16, V12.B16  // F
	VADD V2.S4, V13.S4, V14.S4   // a + X
	MOVD $T_6<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $112, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $17, V12.S4, V11.S4   // x << s
	VUSHR $15, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V3.S4, V12.S4, V2.S4

	// Step 7: R1 g=7 s=22 T=0xfd469501  (a=V1 b=V2 c=V3 d=V0)
	VAND V2.B16, V3.B16, V9.B16   // b & c
	VEOR V8.B16, V2.B16, V10.B16  // ~b
	VAND V10.B16, V0.B16, V10.B16 // ~b & d
	VORR V9.B16, V10.B16, V12.B16  // F
	VADD V1.S4, V13.S4, V14.S4   // a + X
	MOVD $T_7<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $128, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $22, V12.S4, V11.S4   // x << s
	VUSHR $10, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V2.S4, V12.S4, V1.S4

	// Step 8: R1 g=8 s=7 T=0x698098d8  (a=V0 b=V1 c=V2 d=V3)
	VAND V1.B16, V2.B16, V9.B16   // b & c
	VEOR V8.B16, V1.B16, V10.B16  // ~b
	VAND V10.B16, V3.B16, V10.B16 // ~b & d
	VORR V9.B16, V10.B16, V12.B16  // F
	VADD V0.S4, V13.S4, V14.S4   // a + X
	MOVD $T_8<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $144, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $7, V12.S4, V11.S4   // x << s
	VUSHR $25, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V1.S4, V12.S4, V0.S4

	// Step 9: R1 g=9 s=12 T=0x8b44f7af  (a=V3 b=V0 c=V1 d=V2)
	VAND V0.B16, V1.B16, V9.B16   // b & c
	VEOR V8.B16, V0.B16, V10.B16  // ~b
	VAND V10.B16, V2.B16, V10.B16 // ~b & d
	VORR V9.B16, V10.B16, V12.B16  // F
	VADD V3.S4, V13.S4, V14.S4   // a + X
	MOVD $T_9<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $160, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $12, V12.S4, V11.S4   // x << s
	VUSHR $20, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V0.S4, V12.S4, V3.S4

	// Step 10: R1 g=10 s=17 T=0xffff5bb1  (a=V2 b=V3 c=V0 d=V1)
	VAND V3.B16, V0.B16, V9.B16   // b & c
	VEOR V8.B16, V3.B16, V10.B16  // ~b
	VAND V10.B16, V1.B16, V10.B16 // ~b & d
	VORR V9.B16, V10.B16, V12.B16  // F
	VADD V2.S4, V13.S4, V14.S4   // a + X
	MOVD $T_10<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $176, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $17, V12.S4, V11.S4   // x << s
	VUSHR $15, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V3.S4, V12.S4, V2.S4

	// Step 11: R1 g=11 s=22 T=0x895cd7be  (a=V1 b=V2 c=V3 d=V0)
	VAND V2.B16, V3.B16, V9.B16   // b & c
	VEOR V8.B16, V2.B16, V10.B16  // ~b
	VAND V10.B16, V0.B16, V10.B16 // ~b & d
	VORR V9.B16, V10.B16, V12.B16  // F
	VADD V1.S4, V13.S4, V14.S4   // a + X
	MOVD $T_11<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $192, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $22, V12.S4, V11.S4   // x << s
	VUSHR $10, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V2.S4, V12.S4, V1.S4

	// Step 12: R1 g=12 s=7 T=0x6b901122  (a=V0 b=V1 c=V2 d=V3)
	VAND V1.B16, V2.B16, V9.B16   // b & c
	VEOR V8.B16, V1.B16, V10.B16  // ~b
	VAND V10.B16, V3.B16, V10.B16 // ~b & d
	VORR V9.B16, V10.B16, V12.B16  // F
	VADD V0.S4, V13.S4, V14.S4   // a + X
	MOVD $T_12<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $208, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $7, V12.S4, V11.S4   // x << s
	VUSHR $25, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V1.S4, V12.S4, V0.S4

	// Step 13: R1 g=13 s=12 T=0xfd987193  (a=V3 b=V0 c=V1 d=V2)
	VAND V0.B16, V1.B16, V9.B16   // b & c
	VEOR V8.B16, V0.B16, V10.B16  // ~b
	VAND V10.B16, V2.B16, V10.B16 // ~b & d
	VORR V9.B16, V10.B16, V12.B16  // F
	VADD V3.S4, V13.S4, V14.S4   // a + X
	MOVD $T_13<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $224, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $12, V12.S4, V11.S4   // x << s
	VUSHR $20, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V0.S4, V12.S4, V3.S4

	// Step 14: R1 g=14 s=17 T=0xa679438e  (a=V2 b=V3 c=V0 d=V1)
	VAND V3.B16, V0.B16, V9.B16   // b & c
	VEOR V8.B16, V3.B16, V10.B16  // ~b
	VAND V10.B16, V1.B16, V10.B16 // ~b & d
	VORR V9.B16, V10.B16, V12.B16  // F
	VADD V2.S4, V13.S4, V14.S4   // a + X
	MOVD $T_14<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $240, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $17, V12.S4, V11.S4   // x << s
	VUSHR $15, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V3.S4, V12.S4, V2.S4

	// Step 15: R1 g=15 s=22 T=0x49b40821  (a=V1 b=V2 c=V3 d=V0)
	VAND V2.B16, V3.B16, V9.B16   // b & c
	VEOR V8.B16, V2.B16, V10.B16  // ~b
	VAND V10.B16, V0.B16, V10.B16 // ~b & d
	VORR V9.B16, V10.B16, V12.B16  // F
	VADD V1.S4, V13.S4, V14.S4   // a + X
	MOVD $T_15<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $16, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $22, V12.S4, V11.S4   // x << s
	VUSHR $10, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V2.S4, V12.S4, V1.S4

	// Step 16: R2 g=1 s=5 T=0xf61e2562  (a=V0 b=V1 c=V2 d=V3)
	VAND V1.B16, V3.B16, V9.B16   // b & d
	VEOR V8.B16, V3.B16, V10.B16  // ~d
	VAND V2.B16, V10.B16, V10.B16 // c & ~d
	VORR V9.B16, V10.B16, V12.B16  // F
	VADD V0.S4, V13.S4, V14.S4   // a + X
	MOVD $T_16<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $96, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $5, V12.S4, V11.S4   // x << s
	VUSHR $27, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V1.S4, V12.S4, V0.S4

	// Step 17: R2 g=6 s=9 T=0xc040b340  (a=V3 b=V0 c=V1 d=V2)
	VAND V0.B16, V2.B16, V9.B16   // b & d
	VEOR V8.B16, V2.B16, V10.B16  // ~d
	VAND V1.B16, V10.B16, V10.B16 // c & ~d
	VORR V9.B16, V10.B16, V12.B16  // F
	VADD V3.S4, V13.S4, V14.S4   // a + X
	MOVD $T_17<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $176, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $9, V12.S4, V11.S4   // x << s
	VUSHR $23, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V0.S4, V12.S4, V3.S4

	// Step 18: R2 g=11 s=14 T=0x265e5a51  (a=V2 b=V3 c=V0 d=V1)
	VAND V3.B16, V1.B16, V9.B16   // b & d
	VEOR V8.B16, V1.B16, V10.B16  // ~d
	VAND V0.B16, V10.B16, V10.B16 // c & ~d
	VORR V9.B16, V10.B16, V12.B16  // F
	VADD V2.S4, V13.S4, V14.S4   // a + X
	MOVD $T_18<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $0, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $14, V12.S4, V11.S4   // x << s
	VUSHR $18, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V3.S4, V12.S4, V2.S4

	// Step 19: R2 g=0 s=20 T=0xe9b6c7aa  (a=V1 b=V2 c=V3 d=V0)
	VAND V2.B16, V0.B16, V9.B16   // b & d
	VEOR V8.B16, V0.B16, V10.B16  // ~d
	VAND V3.B16, V10.B16, V10.B16 // c & ~d
	VORR V9.B16, V10.B16, V12.B16  // F
	VADD V1.S4, V13.S4, V14.S4   // a + X
	MOVD $T_19<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $80, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $20, V12.S4, V11.S4   // x << s
	VUSHR $12, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V2.S4, V12.S4, V1.S4

	// Step 20: R2 g=5 s=5 T=0xd62f105d  (a=V0 b=V1 c=V2 d=V3)
	VAND V1.B16, V3.B16, V9.B16   // b & d
	VEOR V8.B16, V3.B16, V10.B16  // ~d
	VAND V2.B16, V10.B16, V10.B16 // c & ~d
	VORR V9.B16, V10.B16, V12.B16  // F
	VADD V0.S4, V13.S4, V14.S4   // a + X
	MOVD $T_20<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $160, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $5, V12.S4, V11.S4   // x << s
	VUSHR $27, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V1.S4, V12.S4, V0.S4

	// Step 21: R2 g=10 s=9 T=0x02441453  (a=V3 b=V0 c=V1 d=V2)
	VAND V0.B16, V2.B16, V9.B16   // b & d
	VEOR V8.B16, V2.B16, V10.B16  // ~d
	VAND V1.B16, V10.B16, V10.B16 // c & ~d
	VORR V9.B16, V10.B16, V12.B16  // F
	VADD V3.S4, V13.S4, V14.S4   // a + X
	MOVD $T_21<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $240, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $9, V12.S4, V11.S4   // x << s
	VUSHR $23, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V0.S4, V12.S4, V3.S4

	// Step 22: R2 g=15 s=14 T=0xd8a1e681  (a=V2 b=V3 c=V0 d=V1)
	VAND V3.B16, V1.B16, V9.B16   // b & d
	VEOR V8.B16, V1.B16, V10.B16  // ~d
	VAND V0.B16, V10.B16, V10.B16 // c & ~d
	VORR V9.B16, V10.B16, V12.B16  // F
	VADD V2.S4, V13.S4, V14.S4   // a + X
	MOVD $T_22<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $64, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $14, V12.S4, V11.S4   // x << s
	VUSHR $18, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V3.S4, V12.S4, V2.S4

	// Step 23: R2 g=4 s=20 T=0xe7d3fbc8  (a=V1 b=V2 c=V3 d=V0)
	VAND V2.B16, V0.B16, V9.B16   // b & d
	VEOR V8.B16, V0.B16, V10.B16  // ~d
	VAND V3.B16, V10.B16, V10.B16 // c & ~d
	VORR V9.B16, V10.B16, V12.B16  // F
	VADD V1.S4, V13.S4, V14.S4   // a + X
	MOVD $T_23<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $144, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $20, V12.S4, V11.S4   // x << s
	VUSHR $12, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V2.S4, V12.S4, V1.S4

	// Step 24: R2 g=9 s=5 T=0x21e1cde6  (a=V0 b=V1 c=V2 d=V3)
	VAND V1.B16, V3.B16, V9.B16   // b & d
	VEOR V8.B16, V3.B16, V10.B16  // ~d
	VAND V2.B16, V10.B16, V10.B16 // c & ~d
	VORR V9.B16, V10.B16, V12.B16  // F
	VADD V0.S4, V13.S4, V14.S4   // a + X
	MOVD $T_24<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $224, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $5, V12.S4, V11.S4   // x << s
	VUSHR $27, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V1.S4, V12.S4, V0.S4

	// Step 25: R2 g=14 s=9 T=0xc33707d6  (a=V3 b=V0 c=V1 d=V2)
	VAND V0.B16, V2.B16, V9.B16   // b & d
	VEOR V8.B16, V2.B16, V10.B16  // ~d
	VAND V1.B16, V10.B16, V10.B16 // c & ~d
	VORR V9.B16, V10.B16, V12.B16  // F
	VADD V3.S4, V13.S4, V14.S4   // a + X
	MOVD $T_25<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $48, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $9, V12.S4, V11.S4   // x << s
	VUSHR $23, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V0.S4, V12.S4, V3.S4

	// Step 26: R2 g=3 s=14 T=0xf4d50d87  (a=V2 b=V3 c=V0 d=V1)
	VAND V3.B16, V1.B16, V9.B16   // b & d
	VEOR V8.B16, V1.B16, V10.B16  // ~d
	VAND V0.B16, V10.B16, V10.B16 // c & ~d
	VORR V9.B16, V10.B16, V12.B16  // F
	VADD V2.S4, V13.S4, V14.S4   // a + X
	MOVD $T_26<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $128, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $14, V12.S4, V11.S4   // x << s
	VUSHR $18, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V3.S4, V12.S4, V2.S4

	// Step 27: R2 g=8 s=20 T=0x455a14ed  (a=V1 b=V2 c=V3 d=V0)
	VAND V2.B16, V0.B16, V9.B16   // b & d
	VEOR V8.B16, V0.B16, V10.B16  // ~d
	VAND V3.B16, V10.B16, V10.B16 // c & ~d
	VORR V9.B16, V10.B16, V12.B16  // F
	VADD V1.S4, V13.S4, V14.S4   // a + X
	MOVD $T_27<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $208, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $20, V12.S4, V11.S4   // x << s
	VUSHR $12, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V2.S4, V12.S4, V1.S4

	// Step 28: R2 g=13 s=5 T=0xa9e3e905  (a=V0 b=V1 c=V2 d=V3)
	VAND V1.B16, V3.B16, V9.B16   // b & d
	VEOR V8.B16, V3.B16, V10.B16  // ~d
	VAND V2.B16, V10.B16, V10.B16 // c & ~d
	VORR V9.B16, V10.B16, V12.B16  // F
	VADD V0.S4, V13.S4, V14.S4   // a + X
	MOVD $T_28<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $32, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $5, V12.S4, V11.S4   // x << s
	VUSHR $27, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V1.S4, V12.S4, V0.S4

	// Step 29: R2 g=2 s=9 T=0xfcefa3f8  (a=V3 b=V0 c=V1 d=V2)
	VAND V0.B16, V2.B16, V9.B16   // b & d
	VEOR V8.B16, V2.B16, V10.B16  // ~d
	VAND V1.B16, V10.B16, V10.B16 // c & ~d
	VORR V9.B16, V10.B16, V12.B16  // F
	VADD V3.S4, V13.S4, V14.S4   // a + X
	MOVD $T_29<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $112, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $9, V12.S4, V11.S4   // x << s
	VUSHR $23, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V0.S4, V12.S4, V3.S4

	// Step 30: R2 g=7 s=14 T=0x676f02d9  (a=V2 b=V3 c=V0 d=V1)
	VAND V3.B16, V1.B16, V9.B16   // b & d
	VEOR V8.B16, V1.B16, V10.B16  // ~d
	VAND V0.B16, V10.B16, V10.B16 // c & ~d
	VORR V9.B16, V10.B16, V12.B16  // F
	VADD V2.S4, V13.S4, V14.S4   // a + X
	MOVD $T_30<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $192, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $14, V12.S4, V11.S4   // x << s
	VUSHR $18, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V3.S4, V12.S4, V2.S4

	// Step 31: R2 g=12 s=20 T=0x8d2a4c8a  (a=V1 b=V2 c=V3 d=V0)
	VAND V2.B16, V0.B16, V9.B16   // b & d
	VEOR V8.B16, V0.B16, V10.B16  // ~d
	VAND V3.B16, V10.B16, V10.B16 // c & ~d
	VORR V9.B16, V10.B16, V12.B16  // F
	VADD V1.S4, V13.S4, V14.S4   // a + X
	MOVD $T_31<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $80, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $20, V12.S4, V11.S4   // x << s
	VUSHR $12, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V2.S4, V12.S4, V1.S4

	// Step 32: R3 g=5 s=4 T=0xfffa3942  (a=V0 b=V1 c=V2 d=V3)
	VEOR V1.B16, V2.B16, V12.B16
	VEOR V3.B16, V12.B16, V12.B16
	VADD V0.S4, V13.S4, V14.S4   // a + X
	MOVD $T_32<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $128, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $4, V12.S4, V11.S4   // x << s
	VUSHR $28, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V1.S4, V12.S4, V0.S4

	// Step 33: R3 g=8 s=11 T=0x8771f681  (a=V3 b=V0 c=V1 d=V2)
	VEOR V0.B16, V1.B16, V12.B16
	VEOR V2.B16, V12.B16, V12.B16
	VADD V3.S4, V13.S4, V14.S4   // a + X
	MOVD $T_33<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $176, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $11, V12.S4, V11.S4   // x << s
	VUSHR $21, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V0.S4, V12.S4, V3.S4

	// Step 34: R3 g=11 s=16 T=0x6d9d6122  (a=V2 b=V3 c=V0 d=V1)
	VEOR V3.B16, V0.B16, V12.B16
	VEOR V1.B16, V12.B16, V12.B16
	VADD V2.S4, V13.S4, V14.S4   // a + X
	MOVD $T_34<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $224, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $16, V12.S4, V11.S4   // x << s
	VUSHR $16, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V3.S4, V12.S4, V2.S4

	// Step 35: R3 g=14 s=23 T=0xfde5380c  (a=V1 b=V2 c=V3 d=V0)
	VEOR V2.B16, V3.B16, V12.B16
	VEOR V0.B16, V12.B16, V12.B16
	VADD V1.S4, V13.S4, V14.S4   // a + X
	MOVD $T_35<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $16, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $23, V12.S4, V11.S4   // x << s
	VUSHR $9, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V2.S4, V12.S4, V1.S4

	// Step 36: R3 g=1 s=4 T=0xa4beea44  (a=V0 b=V1 c=V2 d=V3)
	VEOR V1.B16, V2.B16, V12.B16
	VEOR V3.B16, V12.B16, V12.B16
	VADD V0.S4, V13.S4, V14.S4   // a + X
	MOVD $T_36<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $64, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $4, V12.S4, V11.S4   // x << s
	VUSHR $28, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V1.S4, V12.S4, V0.S4

	// Step 37: R3 g=4 s=11 T=0x4bdecfa9  (a=V3 b=V0 c=V1 d=V2)
	VEOR V0.B16, V1.B16, V12.B16
	VEOR V2.B16, V12.B16, V12.B16
	VADD V3.S4, V13.S4, V14.S4   // a + X
	MOVD $T_37<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $112, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $11, V12.S4, V11.S4   // x << s
	VUSHR $21, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V0.S4, V12.S4, V3.S4

	// Step 38: R3 g=7 s=16 T=0xf6bb4b60  (a=V2 b=V3 c=V0 d=V1)
	VEOR V3.B16, V0.B16, V12.B16
	VEOR V1.B16, V12.B16, V12.B16
	VADD V2.S4, V13.S4, V14.S4   // a + X
	MOVD $T_38<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $160, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $16, V12.S4, V11.S4   // x << s
	VUSHR $16, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V3.S4, V12.S4, V2.S4

	// Step 39: R3 g=10 s=23 T=0xbebfbc70  (a=V1 b=V2 c=V3 d=V0)
	VEOR V2.B16, V3.B16, V12.B16
	VEOR V0.B16, V12.B16, V12.B16
	VADD V1.S4, V13.S4, V14.S4   // a + X
	MOVD $T_39<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $208, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $23, V12.S4, V11.S4   // x << s
	VUSHR $9, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V2.S4, V12.S4, V1.S4

	// Step 40: R3 g=13 s=4 T=0x289b7ec6  (a=V0 b=V1 c=V2 d=V3)
	VEOR V1.B16, V2.B16, V12.B16
	VEOR V3.B16, V12.B16, V12.B16
	VADD V0.S4, V13.S4, V14.S4   // a + X
	MOVD $T_40<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $0, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $4, V12.S4, V11.S4   // x << s
	VUSHR $28, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V1.S4, V12.S4, V0.S4

	// Step 41: R3 g=0 s=11 T=0xeaa127fa  (a=V3 b=V0 c=V1 d=V2)
	VEOR V0.B16, V1.B16, V12.B16
	VEOR V2.B16, V12.B16, V12.B16
	VADD V3.S4, V13.S4, V14.S4   // a + X
	MOVD $T_41<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $48, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $11, V12.S4, V11.S4   // x << s
	VUSHR $21, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V0.S4, V12.S4, V3.S4

	// Step 42: R3 g=3 s=16 T=0xd4ef3085  (a=V2 b=V3 c=V0 d=V1)
	VEOR V3.B16, V0.B16, V12.B16
	VEOR V1.B16, V12.B16, V12.B16
	VADD V2.S4, V13.S4, V14.S4   // a + X
	MOVD $T_42<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $96, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $16, V12.S4, V11.S4   // x << s
	VUSHR $16, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V3.S4, V12.S4, V2.S4

	// Step 43: R3 g=6 s=23 T=0x04881d05  (a=V1 b=V2 c=V3 d=V0)
	VEOR V2.B16, V3.B16, V12.B16
	VEOR V0.B16, V12.B16, V12.B16
	VADD V1.S4, V13.S4, V14.S4   // a + X
	MOVD $T_43<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $144, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $23, V12.S4, V11.S4   // x << s
	VUSHR $9, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V2.S4, V12.S4, V1.S4

	// Step 44: R3 g=9 s=4 T=0xd9d4d039  (a=V0 b=V1 c=V2 d=V3)
	VEOR V1.B16, V2.B16, V12.B16
	VEOR V3.B16, V12.B16, V12.B16
	VADD V0.S4, V13.S4, V14.S4   // a + X
	MOVD $T_44<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $192, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $4, V12.S4, V11.S4   // x << s
	VUSHR $28, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V1.S4, V12.S4, V0.S4

	// Step 45: R3 g=12 s=11 T=0xe6db99e5  (a=V3 b=V0 c=V1 d=V2)
	VEOR V0.B16, V1.B16, V12.B16
	VEOR V2.B16, V12.B16, V12.B16
	VADD V3.S4, V13.S4, V14.S4   // a + X
	MOVD $T_45<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $240, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $11, V12.S4, V11.S4   // x << s
	VUSHR $21, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V0.S4, V12.S4, V3.S4

	// Step 46: R3 g=15 s=16 T=0x1fa27cf8  (a=V2 b=V3 c=V0 d=V1)
	VEOR V3.B16, V0.B16, V12.B16
	VEOR V1.B16, V12.B16, V12.B16
	VADD V2.S4, V13.S4, V14.S4   // a + X
	MOVD $T_46<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $32, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $16, V12.S4, V11.S4   // x << s
	VUSHR $16, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V3.S4, V12.S4, V2.S4

	// Step 47: R3 g=2 s=23 T=0xc4ac5665  (a=V1 b=V2 c=V3 d=V0)
	VEOR V2.B16, V3.B16, V12.B16
	VEOR V0.B16, V12.B16, V12.B16
	VADD V1.S4, V13.S4, V14.S4   // a + X
	MOVD $T_47<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $0, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $23, V12.S4, V11.S4   // x << s
	VUSHR $9, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V2.S4, V12.S4, V1.S4

	// Step 48: R4 g=0 s=6 T=0xf4292244  (a=V0 b=V1 c=V2 d=V3)
	VEOR V8.B16, V3.B16, V9.B16   // ~d
	VORR V1.B16, V9.B16, V9.B16   // b | ~d
	VEOR V2.B16, V9.B16, V12.B16  // F
	VADD V0.S4, V13.S4, V14.S4   // a + X
	MOVD $T_48<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $112, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $6, V12.S4, V11.S4   // x << s
	VUSHR $26, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V1.S4, V12.S4, V0.S4

	// Step 49: R4 g=7 s=10 T=0x432aff97  (a=V3 b=V0 c=V1 d=V2)
	VEOR V8.B16, V2.B16, V9.B16   // ~d
	VORR V0.B16, V9.B16, V9.B16   // b | ~d
	VEOR V1.B16, V9.B16, V12.B16  // F
	VADD V3.S4, V13.S4, V14.S4   // a + X
	MOVD $T_49<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $224, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $10, V12.S4, V11.S4   // x << s
	VUSHR $22, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V0.S4, V12.S4, V3.S4

	// Step 50: R4 g=14 s=15 T=0xab9423a7  (a=V2 b=V3 c=V0 d=V1)
	VEOR V8.B16, V1.B16, V9.B16   // ~d
	VORR V3.B16, V9.B16, V9.B16   // b | ~d
	VEOR V0.B16, V9.B16, V12.B16  // F
	VADD V2.S4, V13.S4, V14.S4   // a + X
	MOVD $T_50<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $80, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $15, V12.S4, V11.S4   // x << s
	VUSHR $17, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V3.S4, V12.S4, V2.S4

	// Step 51: R4 g=5 s=21 T=0xfc93a039  (a=V1 b=V2 c=V3 d=V0)
	VEOR V8.B16, V0.B16, V9.B16   // ~d
	VORR V2.B16, V9.B16, V9.B16   // b | ~d
	VEOR V3.B16, V9.B16, V12.B16  // F
	VADD V1.S4, V13.S4, V14.S4   // a + X
	MOVD $T_51<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $192, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $21, V12.S4, V11.S4   // x << s
	VUSHR $11, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V2.S4, V12.S4, V1.S4

	// Step 52: R4 g=12 s=6 T=0x655b59c3  (a=V0 b=V1 c=V2 d=V3)
	VEOR V8.B16, V3.B16, V9.B16   // ~d
	VORR V1.B16, V9.B16, V9.B16   // b | ~d
	VEOR V2.B16, V9.B16, V12.B16  // F
	VADD V0.S4, V13.S4, V14.S4   // a + X
	MOVD $T_52<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $48, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $6, V12.S4, V11.S4   // x << s
	VUSHR $26, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V1.S4, V12.S4, V0.S4

	// Step 53: R4 g=3 s=10 T=0x8f0ccc92  (a=V3 b=V0 c=V1 d=V2)
	VEOR V8.B16, V2.B16, V9.B16   // ~d
	VORR V0.B16, V9.B16, V9.B16   // b | ~d
	VEOR V1.B16, V9.B16, V12.B16  // F
	VADD V3.S4, V13.S4, V14.S4   // a + X
	MOVD $T_53<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $160, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $10, V12.S4, V11.S4   // x << s
	VUSHR $22, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V0.S4, V12.S4, V3.S4

	// Step 54: R4 g=10 s=15 T=0xffeff47d  (a=V2 b=V3 c=V0 d=V1)
	VEOR V8.B16, V1.B16, V9.B16   // ~d
	VORR V3.B16, V9.B16, V9.B16   // b | ~d
	VEOR V0.B16, V9.B16, V12.B16  // F
	VADD V2.S4, V13.S4, V14.S4   // a + X
	MOVD $T_54<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $16, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $15, V12.S4, V11.S4   // x << s
	VUSHR $17, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V3.S4, V12.S4, V2.S4

	// Step 55: R4 g=1 s=21 T=0x85845dd1  (a=V1 b=V2 c=V3 d=V0)
	VEOR V8.B16, V0.B16, V9.B16   // ~d
	VORR V2.B16, V9.B16, V9.B16   // b | ~d
	VEOR V3.B16, V9.B16, V12.B16  // F
	VADD V1.S4, V13.S4, V14.S4   // a + X
	MOVD $T_55<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $128, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $21, V12.S4, V11.S4   // x << s
	VUSHR $11, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V2.S4, V12.S4, V1.S4

	// Step 56: R4 g=8 s=6 T=0x6fa87e4f  (a=V0 b=V1 c=V2 d=V3)
	VEOR V8.B16, V3.B16, V9.B16   // ~d
	VORR V1.B16, V9.B16, V9.B16   // b | ~d
	VEOR V2.B16, V9.B16, V12.B16  // F
	VADD V0.S4, V13.S4, V14.S4   // a + X
	MOVD $T_56<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $240, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $6, V12.S4, V11.S4   // x << s
	VUSHR $26, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V1.S4, V12.S4, V0.S4

	// Step 57: R4 g=15 s=10 T=0xfe2ce6e0  (a=V3 b=V0 c=V1 d=V2)
	VEOR V8.B16, V2.B16, V9.B16   // ~d
	VORR V0.B16, V9.B16, V9.B16   // b | ~d
	VEOR V1.B16, V9.B16, V12.B16  // F
	VADD V3.S4, V13.S4, V14.S4   // a + X
	MOVD $T_57<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $96, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $10, V12.S4, V11.S4   // x << s
	VUSHR $22, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V0.S4, V12.S4, V3.S4

	// Step 58: R4 g=6 s=15 T=0xa3014314  (a=V2 b=V3 c=V0 d=V1)
	VEOR V8.B16, V1.B16, V9.B16   // ~d
	VORR V3.B16, V9.B16, V9.B16   // b | ~d
	VEOR V0.B16, V9.B16, V12.B16  // F
	VADD V2.S4, V13.S4, V14.S4   // a + X
	MOVD $T_58<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $208, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $15, V12.S4, V11.S4   // x << s
	VUSHR $17, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V3.S4, V12.S4, V2.S4

	// Step 59: R4 g=13 s=21 T=0x4e0811a1  (a=V1 b=V2 c=V3 d=V0)
	VEOR V8.B16, V0.B16, V9.B16   // ~d
	VORR V2.B16, V9.B16, V9.B16   // b | ~d
	VEOR V3.B16, V9.B16, V12.B16  // F
	VADD V1.S4, V13.S4, V14.S4   // a + X
	MOVD $T_59<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $64, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $21, V12.S4, V11.S4   // x << s
	VUSHR $11, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V2.S4, V12.S4, V1.S4

	// Step 60: R4 g=4 s=6 T=0xf7537e82  (a=V0 b=V1 c=V2 d=V3)
	VEOR V8.B16, V3.B16, V9.B16   // ~d
	VORR V1.B16, V9.B16, V9.B16   // b | ~d
	VEOR V2.B16, V9.B16, V12.B16  // F
	VADD V0.S4, V13.S4, V14.S4   // a + X
	MOVD $T_60<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $176, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $6, V12.S4, V11.S4   // x << s
	VUSHR $26, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V1.S4, V12.S4, V0.S4

	// Step 61: R4 g=11 s=10 T=0xbd3af235  (a=V3 b=V0 c=V1 d=V2)
	VEOR V8.B16, V2.B16, V9.B16   // ~d
	VORR V0.B16, V9.B16, V9.B16   // b | ~d
	VEOR V1.B16, V9.B16, V12.B16  // F
	VADD V3.S4, V13.S4, V14.S4   // a + X
	MOVD $T_61<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $32, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $10, V12.S4, V11.S4   // x << s
	VUSHR $22, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V0.S4, V12.S4, V3.S4

	// Step 62: R4 g=2 s=15 T=0x2ad7d2bb  (a=V2 b=V3 c=V0 d=V1)
	VEOR V8.B16, V1.B16, V9.B16   // ~d
	VORR V3.B16, V9.B16, V9.B16   // b | ~d
	VEOR V0.B16, V9.B16, V12.B16  // F
	VADD V2.S4, V13.S4, V14.S4   // a + X
	MOVD $T_62<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	ADD $144, R0, R4
	VLD1 (R4), [V13.S4]
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $15, V12.S4, V11.S4   // x << s
	VUSHR $17, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V3.S4, V12.S4, V2.S4

	// Step 63: R4 g=9 s=21 T=0xeb86d391  (a=V1 b=V2 c=V3 d=V0)
	VEOR V8.B16, V0.B16, V9.B16   // ~d
	VORR V2.B16, V9.B16, V9.B16   // b | ~d
	VEOR V3.B16, V9.B16, V12.B16  // F
	VADD V1.S4, V13.S4, V14.S4   // a + X
	MOVD $T_63<>(SB), R3
	VLD1 (R3), [V15.S4]
	VADD V15.S4, V14.S4, V14.S4  // a + X + T
	VADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)
	VSHL $21, V12.S4, V11.S4   // x << s
	VUSHR $11, V12.S4, V12.S4  // x >> (32-s)
	VORR V11.B16, V12.B16, V12.B16  // rotl
	VADD V2.S4, V12.S4, V1.S4

	// Final add-back
	VADD V4.S4, V0.S4, V0.S4
	VADD V5.S4, V1.S4, V1.S4
	VADD V6.S4, V2.S4, V2.S4
	VADD V7.S4, V3.S4, V3.S4

	VST1 [V0.S4, V1.S4, V2.S4, V3.S4], 0(R1)
	RET

DATA allones<>+0(SB)/8,  $0xFFFFFFFFFFFFFFFF
DATA allones<>+8(SB)/8,  $0xFFFFFFFFFFFFFFFF
GLOBL allones<>(SB), RODATA|NOPTR, $16

DATA T_0<>+0(SB)/4, $0xd76aa478
DATA T_0<>+4(SB)/4, $0xd76aa478
DATA T_0<>+8(SB)/4, $0xd76aa478
DATA T_0<>+12(SB)/4, $0xd76aa478
GLOBL T_0<>(SB), RODATA|NOPTR, $16

DATA T_1<>+0(SB)/4, $0xe8c7b756
DATA T_1<>+4(SB)/4, $0xe8c7b756
DATA T_1<>+8(SB)/4, $0xe8c7b756
DATA T_1<>+12(SB)/4, $0xe8c7b756
GLOBL T_1<>(SB), RODATA|NOPTR, $16

DATA T_2<>+0(SB)/4, $0x242070db
DATA T_2<>+4(SB)/4, $0x242070db
DATA T_2<>+8(SB)/4, $0x242070db
DATA T_2<>+12(SB)/4, $0x242070db
GLOBL T_2<>(SB), RODATA|NOPTR, $16

DATA T_3<>+0(SB)/4, $0xc1bdceee
DATA T_3<>+4(SB)/4, $0xc1bdceee
DATA T_3<>+8(SB)/4, $0xc1bdceee
DATA T_3<>+12(SB)/4, $0xc1bdceee
GLOBL T_3<>(SB), RODATA|NOPTR, $16

DATA T_4<>+0(SB)/4, $0xf57c0faf
DATA T_4<>+4(SB)/4, $0xf57c0faf
DATA T_4<>+8(SB)/4, $0xf57c0faf
DATA T_4<>+12(SB)/4, $0xf57c0faf
GLOBL T_4<>(SB), RODATA|NOPTR, $16

DATA T_5<>+0(SB)/4, $0x4787c62a
DATA T_5<>+4(SB)/4, $0x4787c62a
DATA T_5<>+8(SB)/4, $0x4787c62a
DATA T_5<>+12(SB)/4, $0x4787c62a
GLOBL T_5<>(SB), RODATA|NOPTR, $16

DATA T_6<>+0(SB)/4, $0xa8304613
DATA T_6<>+4(SB)/4, $0xa8304613
DATA T_6<>+8(SB)/4, $0xa8304613
DATA T_6<>+12(SB)/4, $0xa8304613
GLOBL T_6<>(SB), RODATA|NOPTR, $16

DATA T_7<>+0(SB)/4, $0xfd469501
DATA T_7<>+4(SB)/4, $0xfd469501
DATA T_7<>+8(SB)/4, $0xfd469501
DATA T_7<>+12(SB)/4, $0xfd469501
GLOBL T_7<>(SB), RODATA|NOPTR, $16

DATA T_8<>+0(SB)/4, $0x698098d8
DATA T_8<>+4(SB)/4, $0x698098d8
DATA T_8<>+8(SB)/4, $0x698098d8
DATA T_8<>+12(SB)/4, $0x698098d8
GLOBL T_8<>(SB), RODATA|NOPTR, $16

DATA T_9<>+0(SB)/4, $0x8b44f7af
DATA T_9<>+4(SB)/4, $0x8b44f7af
DATA T_9<>+8(SB)/4, $0x8b44f7af
DATA T_9<>+12(SB)/4, $0x8b44f7af
GLOBL T_9<>(SB), RODATA|NOPTR, $16

DATA T_10<>+0(SB)/4, $0xffff5bb1
DATA T_10<>+4(SB)/4, $0xffff5bb1
DATA T_10<>+8(SB)/4, $0xffff5bb1
DATA T_10<>+12(SB)/4, $0xffff5bb1
GLOBL T_10<>(SB), RODATA|NOPTR, $16

DATA T_11<>+0(SB)/4, $0x895cd7be
DATA T_11<>+4(SB)/4, $0x895cd7be
DATA T_11<>+8(SB)/4, $0x895cd7be
DATA T_11<>+12(SB)/4, $0x895cd7be
GLOBL T_11<>(SB), RODATA|NOPTR, $16

DATA T_12<>+0(SB)/4, $0x6b901122
DATA T_12<>+4(SB)/4, $0x6b901122
DATA T_12<>+8(SB)/4, $0x6b901122
DATA T_12<>+12(SB)/4, $0x6b901122
GLOBL T_12<>(SB), RODATA|NOPTR, $16

DATA T_13<>+0(SB)/4, $0xfd987193
DATA T_13<>+4(SB)/4, $0xfd987193
DATA T_13<>+8(SB)/4, $0xfd987193
DATA T_13<>+12(SB)/4, $0xfd987193
GLOBL T_13<>(SB), RODATA|NOPTR, $16

DATA T_14<>+0(SB)/4, $0xa679438e
DATA T_14<>+4(SB)/4, $0xa679438e
DATA T_14<>+8(SB)/4, $0xa679438e
DATA T_14<>+12(SB)/4, $0xa679438e
GLOBL T_14<>(SB), RODATA|NOPTR, $16

DATA T_15<>+0(SB)/4, $0x49b40821
DATA T_15<>+4(SB)/4, $0x49b40821
DATA T_15<>+8(SB)/4, $0x49b40821
DATA T_15<>+12(SB)/4, $0x49b40821
GLOBL T_15<>(SB), RODATA|NOPTR, $16

DATA T_16<>+0(SB)/4, $0xf61e2562
DATA T_16<>+4(SB)/4, $0xf61e2562
DATA T_16<>+8(SB)/4, $0xf61e2562
DATA T_16<>+12(SB)/4, $0xf61e2562
GLOBL T_16<>(SB), RODATA|NOPTR, $16

DATA T_17<>+0(SB)/4, $0xc040b340
DATA T_17<>+4(SB)/4, $0xc040b340
DATA T_17<>+8(SB)/4, $0xc040b340
DATA T_17<>+12(SB)/4, $0xc040b340
GLOBL T_17<>(SB), RODATA|NOPTR, $16

DATA T_18<>+0(SB)/4, $0x265e5a51
DATA T_18<>+4(SB)/4, $0x265e5a51
DATA T_18<>+8(SB)/4, $0x265e5a51
DATA T_18<>+12(SB)/4, $0x265e5a51
GLOBL T_18<>(SB), RODATA|NOPTR, $16

DATA T_19<>+0(SB)/4, $0xe9b6c7aa
DATA T_19<>+4(SB)/4, $0xe9b6c7aa
DATA T_19<>+8(SB)/4, $0xe9b6c7aa
DATA T_19<>+12(SB)/4, $0xe9b6c7aa
GLOBL T_19<>(SB), RODATA|NOPTR, $16

DATA T_20<>+0(SB)/4, $0xd62f105d
DATA T_20<>+4(SB)/4, $0xd62f105d
DATA T_20<>+8(SB)/4, $0xd62f105d
DATA T_20<>+12(SB)/4, $0xd62f105d
GLOBL T_20<>(SB), RODATA|NOPTR, $16

DATA T_21<>+0(SB)/4, $0x02441453
DATA T_21<>+4(SB)/4, $0x02441453
DATA T_21<>+8(SB)/4, $0x02441453
DATA T_21<>+12(SB)/4, $0x02441453
GLOBL T_21<>(SB), RODATA|NOPTR, $16

DATA T_22<>+0(SB)/4, $0xd8a1e681
DATA T_22<>+4(SB)/4, $0xd8a1e681
DATA T_22<>+8(SB)/4, $0xd8a1e681
DATA T_22<>+12(SB)/4, $0xd8a1e681
GLOBL T_22<>(SB), RODATA|NOPTR, $16

DATA T_23<>+0(SB)/4, $0xe7d3fbc8
DATA T_23<>+4(SB)/4, $0xe7d3fbc8
DATA T_23<>+8(SB)/4, $0xe7d3fbc8
DATA T_23<>+12(SB)/4, $0xe7d3fbc8
GLOBL T_23<>(SB), RODATA|NOPTR, $16

DATA T_24<>+0(SB)/4, $0x21e1cde6
DATA T_24<>+4(SB)/4, $0x21e1cde6
DATA T_24<>+8(SB)/4, $0x21e1cde6
DATA T_24<>+12(SB)/4, $0x21e1cde6
GLOBL T_24<>(SB), RODATA|NOPTR, $16

DATA T_25<>+0(SB)/4, $0xc33707d6
DATA T_25<>+4(SB)/4, $0xc33707d6
DATA T_25<>+8(SB)/4, $0xc33707d6
DATA T_25<>+12(SB)/4, $0xc33707d6
GLOBL T_25<>(SB), RODATA|NOPTR, $16

DATA T_26<>+0(SB)/4, $0xf4d50d87
DATA T_26<>+4(SB)/4, $0xf4d50d87
DATA T_26<>+8(SB)/4, $0xf4d50d87
DATA T_26<>+12(SB)/4, $0xf4d50d87
GLOBL T_26<>(SB), RODATA|NOPTR, $16

DATA T_27<>+0(SB)/4, $0x455a14ed
DATA T_27<>+4(SB)/4, $0x455a14ed
DATA T_27<>+8(SB)/4, $0x455a14ed
DATA T_27<>+12(SB)/4, $0x455a14ed
GLOBL T_27<>(SB), RODATA|NOPTR, $16

DATA T_28<>+0(SB)/4, $0xa9e3e905
DATA T_28<>+4(SB)/4, $0xa9e3e905
DATA T_28<>+8(SB)/4, $0xa9e3e905
DATA T_28<>+12(SB)/4, $0xa9e3e905
GLOBL T_28<>(SB), RODATA|NOPTR, $16

DATA T_29<>+0(SB)/4, $0xfcefa3f8
DATA T_29<>+4(SB)/4, $0xfcefa3f8
DATA T_29<>+8(SB)/4, $0xfcefa3f8
DATA T_29<>+12(SB)/4, $0xfcefa3f8
GLOBL T_29<>(SB), RODATA|NOPTR, $16

DATA T_30<>+0(SB)/4, $0x676f02d9
DATA T_30<>+4(SB)/4, $0x676f02d9
DATA T_30<>+8(SB)/4, $0x676f02d9
DATA T_30<>+12(SB)/4, $0x676f02d9
GLOBL T_30<>(SB), RODATA|NOPTR, $16

DATA T_31<>+0(SB)/4, $0x8d2a4c8a
DATA T_31<>+4(SB)/4, $0x8d2a4c8a
DATA T_31<>+8(SB)/4, $0x8d2a4c8a
DATA T_31<>+12(SB)/4, $0x8d2a4c8a
GLOBL T_31<>(SB), RODATA|NOPTR, $16

DATA T_32<>+0(SB)/4, $0xfffa3942
DATA T_32<>+4(SB)/4, $0xfffa3942
DATA T_32<>+8(SB)/4, $0xfffa3942
DATA T_32<>+12(SB)/4, $0xfffa3942
GLOBL T_32<>(SB), RODATA|NOPTR, $16

DATA T_33<>+0(SB)/4, $0x8771f681
DATA T_33<>+4(SB)/4, $0x8771f681
DATA T_33<>+8(SB)/4, $0x8771f681
DATA T_33<>+12(SB)/4, $0x8771f681
GLOBL T_33<>(SB), RODATA|NOPTR, $16

DATA T_34<>+0(SB)/4, $0x6d9d6122
DATA T_34<>+4(SB)/4, $0x6d9d6122
DATA T_34<>+8(SB)/4, $0x6d9d6122
DATA T_34<>+12(SB)/4, $0x6d9d6122
GLOBL T_34<>(SB), RODATA|NOPTR, $16

DATA T_35<>+0(SB)/4, $0xfde5380c
DATA T_35<>+4(SB)/4, $0xfde5380c
DATA T_35<>+8(SB)/4, $0xfde5380c
DATA T_35<>+12(SB)/4, $0xfde5380c
GLOBL T_35<>(SB), RODATA|NOPTR, $16

DATA T_36<>+0(SB)/4, $0xa4beea44
DATA T_36<>+4(SB)/4, $0xa4beea44
DATA T_36<>+8(SB)/4, $0xa4beea44
DATA T_36<>+12(SB)/4, $0xa4beea44
GLOBL T_36<>(SB), RODATA|NOPTR, $16

DATA T_37<>+0(SB)/4, $0x4bdecfa9
DATA T_37<>+4(SB)/4, $0x4bdecfa9
DATA T_37<>+8(SB)/4, $0x4bdecfa9
DATA T_37<>+12(SB)/4, $0x4bdecfa9
GLOBL T_37<>(SB), RODATA|NOPTR, $16

DATA T_38<>+0(SB)/4, $0xf6bb4b60
DATA T_38<>+4(SB)/4, $0xf6bb4b60
DATA T_38<>+8(SB)/4, $0xf6bb4b60
DATA T_38<>+12(SB)/4, $0xf6bb4b60
GLOBL T_38<>(SB), RODATA|NOPTR, $16

DATA T_39<>+0(SB)/4, $0xbebfbc70
DATA T_39<>+4(SB)/4, $0xbebfbc70
DATA T_39<>+8(SB)/4, $0xbebfbc70
DATA T_39<>+12(SB)/4, $0xbebfbc70
GLOBL T_39<>(SB), RODATA|NOPTR, $16

DATA T_40<>+0(SB)/4, $0x289b7ec6
DATA T_40<>+4(SB)/4, $0x289b7ec6
DATA T_40<>+8(SB)/4, $0x289b7ec6
DATA T_40<>+12(SB)/4, $0x289b7ec6
GLOBL T_40<>(SB), RODATA|NOPTR, $16

DATA T_41<>+0(SB)/4, $0xeaa127fa
DATA T_41<>+4(SB)/4, $0xeaa127fa
DATA T_41<>+8(SB)/4, $0xeaa127fa
DATA T_41<>+12(SB)/4, $0xeaa127fa
GLOBL T_41<>(SB), RODATA|NOPTR, $16

DATA T_42<>+0(SB)/4, $0xd4ef3085
DATA T_42<>+4(SB)/4, $0xd4ef3085
DATA T_42<>+8(SB)/4, $0xd4ef3085
DATA T_42<>+12(SB)/4, $0xd4ef3085
GLOBL T_42<>(SB), RODATA|NOPTR, $16

DATA T_43<>+0(SB)/4, $0x04881d05
DATA T_43<>+4(SB)/4, $0x04881d05
DATA T_43<>+8(SB)/4, $0x04881d05
DATA T_43<>+12(SB)/4, $0x04881d05
GLOBL T_43<>(SB), RODATA|NOPTR, $16

DATA T_44<>+0(SB)/4, $0xd9d4d039
DATA T_44<>+4(SB)/4, $0xd9d4d039
DATA T_44<>+8(SB)/4, $0xd9d4d039
DATA T_44<>+12(SB)/4, $0xd9d4d039
GLOBL T_44<>(SB), RODATA|NOPTR, $16

DATA T_45<>+0(SB)/4, $0xe6db99e5
DATA T_45<>+4(SB)/4, $0xe6db99e5
DATA T_45<>+8(SB)/4, $0xe6db99e5
DATA T_45<>+12(SB)/4, $0xe6db99e5
GLOBL T_45<>(SB), RODATA|NOPTR, $16

DATA T_46<>+0(SB)/4, $0x1fa27cf8
DATA T_46<>+4(SB)/4, $0x1fa27cf8
DATA T_46<>+8(SB)/4, $0x1fa27cf8
DATA T_46<>+12(SB)/4, $0x1fa27cf8
GLOBL T_46<>(SB), RODATA|NOPTR, $16

DATA T_47<>+0(SB)/4, $0xc4ac5665
DATA T_47<>+4(SB)/4, $0xc4ac5665
DATA T_47<>+8(SB)/4, $0xc4ac5665
DATA T_47<>+12(SB)/4, $0xc4ac5665
GLOBL T_47<>(SB), RODATA|NOPTR, $16

DATA T_48<>+0(SB)/4, $0xf4292244
DATA T_48<>+4(SB)/4, $0xf4292244
DATA T_48<>+8(SB)/4, $0xf4292244
DATA T_48<>+12(SB)/4, $0xf4292244
GLOBL T_48<>(SB), RODATA|NOPTR, $16

DATA T_49<>+0(SB)/4, $0x432aff97
DATA T_49<>+4(SB)/4, $0x432aff97
DATA T_49<>+8(SB)/4, $0x432aff97
DATA T_49<>+12(SB)/4, $0x432aff97
GLOBL T_49<>(SB), RODATA|NOPTR, $16

DATA T_50<>+0(SB)/4, $0xab9423a7
DATA T_50<>+4(SB)/4, $0xab9423a7
DATA T_50<>+8(SB)/4, $0xab9423a7
DATA T_50<>+12(SB)/4, $0xab9423a7
GLOBL T_50<>(SB), RODATA|NOPTR, $16

DATA T_51<>+0(SB)/4, $0xfc93a039
DATA T_51<>+4(SB)/4, $0xfc93a039
DATA T_51<>+8(SB)/4, $0xfc93a039
DATA T_51<>+12(SB)/4, $0xfc93a039
GLOBL T_51<>(SB), RODATA|NOPTR, $16

DATA T_52<>+0(SB)/4, $0x655b59c3
DATA T_52<>+4(SB)/4, $0x655b59c3
DATA T_52<>+8(SB)/4, $0x655b59c3
DATA T_52<>+12(SB)/4, $0x655b59c3
GLOBL T_52<>(SB), RODATA|NOPTR, $16

DATA T_53<>+0(SB)/4, $0x8f0ccc92
DATA T_53<>+4(SB)/4, $0x8f0ccc92
DATA T_53<>+8(SB)/4, $0x8f0ccc92
DATA T_53<>+12(SB)/4, $0x8f0ccc92
GLOBL T_53<>(SB), RODATA|NOPTR, $16

DATA T_54<>+0(SB)/4, $0xffeff47d
DATA T_54<>+4(SB)/4, $0xffeff47d
DATA T_54<>+8(SB)/4, $0xffeff47d
DATA T_54<>+12(SB)/4, $0xffeff47d
GLOBL T_54<>(SB), RODATA|NOPTR, $16

DATA T_55<>+0(SB)/4, $0x85845dd1
DATA T_55<>+4(SB)/4, $0x85845dd1
DATA T_55<>+8(SB)/4, $0x85845dd1
DATA T_55<>+12(SB)/4, $0x85845dd1
GLOBL T_55<>(SB), RODATA|NOPTR, $16

DATA T_56<>+0(SB)/4, $0x6fa87e4f
DATA T_56<>+4(SB)/4, $0x6fa87e4f
DATA T_56<>+8(SB)/4, $0x6fa87e4f
DATA T_56<>+12(SB)/4, $0x6fa87e4f
GLOBL T_56<>(SB), RODATA|NOPTR, $16

DATA T_57<>+0(SB)/4, $0xfe2ce6e0
DATA T_57<>+4(SB)/4, $0xfe2ce6e0
DATA T_57<>+8(SB)/4, $0xfe2ce6e0
DATA T_57<>+12(SB)/4, $0xfe2ce6e0
GLOBL T_57<>(SB), RODATA|NOPTR, $16

DATA T_58<>+0(SB)/4, $0xa3014314
DATA T_58<>+4(SB)/4, $0xa3014314
DATA T_58<>+8(SB)/4, $0xa3014314
DATA T_58<>+12(SB)/4, $0xa3014314
GLOBL T_58<>(SB), RODATA|NOPTR, $16

DATA T_59<>+0(SB)/4, $0x4e0811a1
DATA T_59<>+4(SB)/4, $0x4e0811a1
DATA T_59<>+8(SB)/4, $0x4e0811a1
DATA T_59<>+12(SB)/4, $0x4e0811a1
GLOBL T_59<>(SB), RODATA|NOPTR, $16

DATA T_60<>+0(SB)/4, $0xf7537e82
DATA T_60<>+4(SB)/4, $0xf7537e82
DATA T_60<>+8(SB)/4, $0xf7537e82
DATA T_60<>+12(SB)/4, $0xf7537e82
GLOBL T_60<>(SB), RODATA|NOPTR, $16

DATA T_61<>+0(SB)/4, $0xbd3af235
DATA T_61<>+4(SB)/4, $0xbd3af235
DATA T_61<>+8(SB)/4, $0xbd3af235
DATA T_61<>+12(SB)/4, $0xbd3af235
GLOBL T_61<>(SB), RODATA|NOPTR, $16

DATA T_62<>+0(SB)/4, $0x2ad7d2bb
DATA T_62<>+4(SB)/4, $0x2ad7d2bb
DATA T_62<>+8(SB)/4, $0x2ad7d2bb
DATA T_62<>+12(SB)/4, $0x2ad7d2bb
GLOBL T_62<>(SB), RODATA|NOPTR, $16

DATA T_63<>+0(SB)/4, $0xeb86d391
DATA T_63<>+4(SB)/4, $0xeb86d391
DATA T_63<>+8(SB)/4, $0xeb86d391
DATA T_63<>+12(SB)/4, $0xeb86d391
GLOBL T_63<>(SB), RODATA|NOPTR, $16

