//go:build ignore

package main

import (
	"fmt"
	"os"
)

func main() {
	f, err := os.Create("../md5x8_amd64.s")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	w := func(s string, args ...interface{}) {
		fmt.Fprintf(f, s+"\n", args...)
	}

	w("// Code generated by gen_md5x8; DO NOT EDIT.")
	w("// 8-way MD5 AVX2 â€?64 unrolled steps for 8 parallel blocks.")
	w("")
	w("#include \"textflag.h\"")
	w("")
	w("// func md5x8core(x *[16][8]uint32, state *[4][8]uint32)")
	w("TEXT Â·md5x8core(SB), NOSPLIT, $0-16")
	w("\tMOVQ x+0(FP), DI")
	w("\tMOVQ state+8(FP), SI")
	w("")
	w("\tVMOVDQU 0(SI), Y8")
	w("\tVMOVDQU 32(SI), Y9")
	w("\tVMOVDQU 64(SI), Y10")
	w("\tVMOVDQU 96(SI), Y11")
	w("\tVMOVDQU allones<>+0(SB), Y7")
	w("")

	T := [64]uint32{
		0xd76aa478, 0xe8c7b756, 0x242070db, 0xc1bdceee,
		0xf57c0faf, 0x4787c62a, 0xa8304613, 0xfd469501,
		0x698098d8, 0x8b44f7af, 0xffff5bb1, 0x895cd7be,
		0x6b901122, 0xfd987193, 0xa679438e, 0x49b40821,
		0xf61e2562, 0xc040b340, 0x265e5a51, 0xe9b6c7aa,
		0xd62f105d, 0x02441453, 0xd8a1e681, 0xe7d3fbc8,
		0x21e1cde6, 0xc33707d6, 0xf4d50d87, 0x455a14ed,
		0xa9e3e905, 0xfcefa3f8, 0x676f02d9, 0x8d2a4c8a,
		0xfffa3942, 0x8771f681, 0x6d9d6122, 0xfde5380c,
		0xa4beea44, 0x4bdecfa9, 0xf6bb4b60, 0xbebfbc70,
		0x289b7ec6, 0xeaa127fa, 0xd4ef3085, 0x04881d05,
		0xd9d4d039, 0xe6db99e5, 0x1fa27cf8, 0xc4ac5665,
		0xf4292244, 0x432aff97, 0xab9423a7, 0xfc93a039,
		0x655b59c3, 0x8f0ccc92, 0xffeff47d, 0x85845dd1,
		0x6fa87e4f, 0xfe2ce6e0, 0xa3014314, 0x4e0811a1,
		0xf7537e82, 0xbd3af235, 0x2ad7d2bb, 0xeb86d391,
	}

	shifts := [64]int{}
	gVals := [64]int{}
	for i := 0; i < 64; i++ {
		switch {
		case i < 16:
			gVals[i] = i
			shifts[i] = []int{7, 12, 17, 22}[i%4]
		case i < 32:
			gVals[i] = (5*i + 1) % 16
			shifts[i] = []int{5, 9, 14, 20}[i%4]
		case i < 48:
			gVals[i] = (3*i + 5) % 16
			shifts[i] = []int{4, 11, 16, 23}[i%4]
		default:
			gVals[i] = (7 * i) % 16
			shifts[i] = []int{6, 10, 15, 21}[i%4]
		}
	}

	// Emit 64 steps
	for i := 0; i < 64; i++ {
		g := gVals[i]
		s := shifts[i]
		round := i / 16 // 0-based round (0=Round1, 1=Round2, 2=Round3, 3=Round4)

		w("\t// Step %d: R%d g=%d s=%d T=0x%08x", i, round+1, g, s, T[i])

		// Load X[g]
		w("\tVMOVDQU %d(DI), Y14", g*32)

		// Round function
		switch round {
		case 0:
			w("\tVPAND  Y9, Y10, Y12")
			w("\tVPANDN Y9, Y11, Y13")
			w("\tVPOR   Y12, Y13, Y12")
		case 1:
			w("\tVPAND  Y9, Y11, Y12")
			w("\tVPANDN Y11, Y10, Y13")
			w("\tVPOR   Y12, Y13, Y12")
		case 2:
			w("\tVPXOR  Y9, Y10, Y12")
			w("\tVPXOR  Y12, Y11, Y12")
		case 3:
			w("\tVPANDN Y9, Y11, Y13")
			w("\tVPXOR  Y7, Y13, Y13")
			w("\tVPXOR  Y13, Y10, Y12")
		}

		// f += a + X[g] + T[i]
		w("\tVPADDD Y8, Y12, Y12")
		w("\tVPADDD Y14, Y12, Y12")
		w("\tVMOVDQU T_%d<>+0(SB), Y15", i)
		w("\tVPADDD Y15, Y12, Y12")

		// rotl by s
		w("\tVPSLLD $%d, Y12, Y13", s)
		w("\tVPSRLD $%d, Y12, Y12", 32-s)
		w("\tVPOR   Y12, Y13, Y12")

		// State rotation
		w("\tVMOVDQA Y9, Y13")
		w("\tVMOVDQA Y10, Y1")
		w("\tVPADDD  Y9, Y12, Y12")
		w("\tVMOVDQA Y11, Y8")
		w("\tVMOVDQA Y12, Y9")
		w("\tVMOVDQA Y13, Y10")
		w("\tVMOVDQA Y1, Y11")
		w("")
	}

	// Store state
	w("\tVMOVDQU Y8, 0(SI)")
	w("\tVMOVDQU Y9, 32(SI)")
	w("\tVMOVDQU Y10, 64(SI)")
	w("\tVMOVDQU Y11, 96(SI)")
	w("\tVZEROUPPER")
	w("\tRET")
	w("")

	// Tables
	w("DATA allones<>+0(SB)/8,  $0xFFFFFFFFFFFFFFFF")
	w("DATA allones<>+8(SB)/8,  $0xFFFFFFFFFFFFFFFF")
	w("DATA allones<>+16(SB)/8, $0xFFFFFFFFFFFFFFFF")
	w("DATA allones<>+24(SB)/8, $0xFFFFFFFFFFFFFFFF")
	w("GLOBL allones<>(SB), RODATA|NOPTR, $32")
	w("")

	for i, t := range T {
		w("DATA T_%d<>+0(SB)/4, $0x%08x", i, t)
		w("DATA T_%d<>+4(SB)/4, $0x%08x", i, t)
		w("DATA T_%d<>+8(SB)/4, $0x%08x", i, t)
		w("DATA T_%d<>+12(SB)/4, $0x%08x", i, t)
		w("DATA T_%d<>+16(SB)/4, $0x%08x", i, t)
		w("DATA T_%d<>+20(SB)/4, $0x%08x", i, t)
		w("DATA T_%d<>+24(SB)/4, $0x%08x", i, t)
		w("DATA T_%d<>+28(SB)/4, $0x%08x", i, t)
		w("GLOBL T_%d<>(SB), RODATA|NOPTR, $32", i)
		w("")
	}
}
