// Package hashsimd provides SIMD-accelerated MD5 for hashing many small
// blocks in parallel.
//
// It is the strong-hash engine behind go-rsync's signature generation, split
// out into its own module so it can be reused independently: any workload
// that hashes N independent buffers (block dedup, delta sync, chunk indexing)
// benefits from the parallel lanes without pulling in the whole delta stack.
//
// # Supported paths (auto-dispatched by build tags + CPU detection)
//
//   - 8-way AVX2 (amd64): 8 blocks hashed in parallel via YMM assembly.
//   - 16-way AVX-512 (amd64): 16 blocks in parallel via ZMM (gather + transpose).
//   - 4-way NEON (arm64): 4 blocks in parallel via ARM64 NEON assembly.
//   - Stubs on other platforms: availability functions return false.
//
// The public entry points are [MD5Hash8way], [MD5Hash16way] and [MD5Hash4way].
// Each expects all blocks to share the same length, and a pre-allocated
// contiguous output buffer ([8]/[16]/[4] × [16]byte). Callers must check the
// matching availability function first (e.g. [MD5x8Available]); calling a
// hash function on an unsupported CPU/GOARCH panics.
//
// # Performance (Ryzen 9 8940HX, Zen 4)
//
//	MD5x8Core_Bulk  (AVX2 raw)       ~6.31 GB/s
//	MD5x16Core_Bulk (AVX-512 raw)    ~11.24 GB/s
//
// See go-rsync's README / docs for the full benchmark tables.
//
// # Code generators
//
// The 8-way/16-way/4-way assembly is generated by gen_md5x8/, gen_md5x16/ and
// gen_md5x4/ in this directory. Run `cd hashsimd/gen_md5x8 && go run .` etc.
// to regenerate the .s files.
package hashsimd

// MD5x8Available reports whether the 8-way AVX2 MD5 path is usable on this
// CPU/GOARCH (amd64 with AVX2).
func MD5x8Available() bool { return md5x8available() }

// MD5x16Available reports whether the 16-way AVX-512 MD5 path is usable on
// this CPU/GOARCH (amd64 with AVX-512F + AVX-512DQ).
func MD5x16Available() bool { return md5x16available() }

// MD5x4Available reports whether the 4-way NEON MD5 path is usable on this
// CPU/GOARCH (arm64 with ASIMD).
func MD5x4Available() bool { return md5x4available() }

// MD5Hash8way hashes 8 blocks in parallel using the 8-way AVX2 path
// (amd64). data holds the blocks at the given offsets; all 8 lengths must be
// equal (typically blockSize). out receives the 8 digests.
// Requires MD5x8Available; panics otherwise.
func MD5Hash8way(data []byte, offsets [8]int, lengths [8]int, out *[8][16]byte) {
	md5Hash8wayAVX2(data, offsets, lengths, out)
}

// MD5Hash16way hashes 16 blocks in parallel using the 16-way AVX-512 path
// (amd64). All 16 lengths must be equal. out receives the 16 digests.
// Requires MD5x16Available; panics otherwise.
func MD5Hash16way(data []byte, offsets [16]int, lengths [16]int, out *[16][16]byte) {
	md5Hash16wayAVX512(data, offsets, lengths, out)
}

// MD5Hash4way hashes 4 blocks in parallel using the 4-way NEON path
// (arm64). All 4 lengths must be equal. out receives the 4 digests.
// Requires MD5x4Available; panics otherwise.
func MD5Hash4way(data []byte, offsets [4]int, lengths [4]int, out *[4][16]byte) {
	md5Hash4wayNEON(data, offsets, lengths, out)
}
