// Code generator for 4-way MD5 ARM64 NEON assembly.
// Produces md5x4_arm64.s with 64 unrolled steps and implicit register rotation.
//
// Usage: cd gen_md5x4 && go run .
package main

import (
	"fmt"
	"os"
)

func main() {
	f, err := os.Create("../md5x4_arm64.s")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	w := func(s string, args ...interface{}) {
		fmt.Fprintf(f, s+"\n", args...)
	}

	w("// Code generated by gen_md5x4; DO NOT EDIT.")
	w("// 4-way MD5 ARM64 NEON — 64 unrolled steps with implicit register rotation.")
	w("// Processes 4 blocks of 64 bytes in parallel using Vn.4S (128-bit) registers.")
	w("")
	w("#include \"textflag.h\"")
	w("")
	w("// func md5x4core(x *[16][4]uint32, state *[4][4]uint32)")
	w("TEXT ·md5x4core(SB), NOSPLIT, $0-16")
	w("\tMOVD x+0(FP), R0")
	w("\tMOVD state+8(FP), R1")
	w("")
	// State: V0=a, V1=b, V2=c, V3=d (roles rotate per step)
	// Saved: V4=sa, V5=sb, V6=sc, V7=sd
	// Const: V8=allones
	// Work:  V9,V10=F temps+aux, V11=rotl tmp, V12=F|rotl result, V13=X[g], V14=accumulator
	w("\tVLD1 0(R1), [V0.4S, V1.4S, V2.4S, V3.4S]")
	w("\t// Load all-ones constant")
	w("\tVMOV allones<>+0(SB), V8.S4")
	w("")
	w("\t// Save initial state for final add-back")
	w("\tVMOV V0.B16, V4.B16")
	w("\tVMOV V1.B16, V5.B16")
	w("\tVMOV V2.B16, V6.B16")
	w("\tVMOV V3.B16, V7.B16")
	w("")

	T := [64]uint32{
		0xd76aa478, 0xe8c7b756, 0x242070db, 0xc1bdceee,
		0xf57c0faf, 0x4787c62a, 0xa8304613, 0xfd469501,
		0x698098d8, 0x8b44f7af, 0xffff5bb1, 0x895cd7be,
		0x6b901122, 0xfd987193, 0xa679438e, 0x49b40821,
		0xf61e2562, 0xc040b340, 0x265e5a51, 0xe9b6c7aa,
		0xd62f105d, 0x02441453, 0xd8a1e681, 0xe7d3fbc8,
		0x21e1cde6, 0xc33707d6, 0xf4d50d87, 0x455a14ed,
		0xa9e3e905, 0xfcefa3f8, 0x676f02d9, 0x8d2a4c8a,
		0xfffa3942, 0x8771f681, 0x6d9d6122, 0xfde5380c,
		0xa4beea44, 0x4bdecfa9, 0xf6bb4b60, 0xbebfbc70,
		0x289b7ec6, 0xeaa127fa, 0xd4ef3085, 0x04881d05,
		0xd9d4d039, 0xe6db99e5, 0x1fa27cf8, 0xc4ac5665,
		0xf4292244, 0x432aff97, 0xab9423a7, 0xfc93a039,
		0x655b59c3, 0x8f0ccc92, 0xffeff47d, 0x85845dd1,
		0x6fa87e4f, 0xfe2ce6e0, 0xa3014314, 0x4e0811a1,
		0xf7537e82, 0xbd3af235, 0x2ad7d2bb, 0xeb86d391,
	}

	shifts := [64]int{}
	gVals := [64]int{}
	for i := 0; i < 64; i++ {
		switch {
		case i < 16:
			gVals[i] = i
			shifts[i] = []int{7, 12, 17, 22}[i%4]
		case i < 32:
			gVals[i] = (5*i + 1) % 16
			shifts[i] = []int{5, 9, 14, 20}[i%4]
		case i < 48:
			gVals[i] = (3*i + 5) % 16
			shifts[i] = []int{4, 11, 16, 23}[i%4]
		default:
			gVals[i] = (7 * i) % 16
			shifts[i] = []int{6, 10, 15, 21}[i%4]
		}
	}

	// Register permutation: logical (a,b,c,d) → physical V0-V3
	perm := [4][4]int{
		{0, 1, 2, 3}, // i%4==0: a=V0, b=V1, c=V2, d=V3
		{3, 0, 1, 2}, // i%4==1: a=V3, b=V0, c=V1, d=V2
		{2, 3, 0, 1}, // i%4==2: a=V2, b=V3, c=V0, d=V1
		{1, 2, 3, 0}, // i%4==3: a=V1, b=V2, c=V3, d=V0
	}

	phys := func(idx int) string { return fmt.Sprintf("V%d", idx) }

	// Preload X[0]
	w("\tVLD1 %d(R0), [V13.4S]", gVals[0]*16)
	w("")

	// Emit 64 steps
	for i := 0; i < 64; i++ {
		g := gVals[i]
		s := shifts[i]
		round := i / 16

		p := perm[i%4]
		rA := phys(p[0])
		rB := phys(p[1])
		rC := phys(p[2])
		rD := phys(p[3])

		w("\t// Step %d: R%d g=%d s=%d T=0x%08x  (a=%s b=%s c=%s d=%s)",
			i, round+1, g, s, T[i], rA, rB, rC, rD)

		// Round function → F in V12
		// NEON: VAND Vn,Vm,Vd → Vd=Vn&Vm; VBIC Vn,Vm,Vd → Vd=Vm&~Vn
		// VEOR Vn,Vm,Vd → Vd=Vn^Vm; VORR Vn,Vm,Vd → Vd=Vn|Vm
		switch round {
		case 0: // F = (b&c) | (~b&d) = (b&c) | (d&~b)
			w("\tVAND %s.S4, %s.S4, V9.S4   // V9 = b & c", rB, rC)
			w("\tVBIC %s.S4, %s.S4, V10.S4  // V10 = d & ~b", rB, rD)
			w("\tVORR V9.B16, V10.B16, V12.B16")
		case 1: // F = (b&d) | (c&~d)
			w("\tVAND %s.S4, %s.S4, V9.S4   // V9 = b & d", rB, rD)
			w("\tVBIC %s.S4, %s.S4, V10.S4  // V10 = c & ~d", rD, rC)
			w("\tVORR V9.B16, V10.B16, V12.B16")
		case 2: // F = b ^ c ^ d
			w("\tVEOR %s.B16, %s.B16, V12.B16", rB, rC)
			w("\tVEOR %s.B16, V12.B16, V12.B16", rD)
		case 3: // F = c ^ (b | ~d) = c ^ ~(~b & d)
			w("\tVBIC %s.S4, %s.S4, V9.S4   // V9 = d & ~b", rB, rD)
			w("\tVEOR V8.B16, V9.B16, V9.B16  // V9 = ~(d&~b) = b|~d")
			w("\tVEOR %s.B16, V9.B16, V12.B16    // V12 = c ^ (b|~d)", rC)
		}

		// a + X[g] + T
		w("\tVADD %s.S4, V13.S4, V14.S4   // a + X", rA)
		w("\tVADD T_%d<>+0(SB), V14.S4, V14.S4  // a + X + T", i)

		// Prefetch next X
		if i < 63 {
			w("\tVLD1 %d(R0), [V13.4S]", gVals[i+1]*16)
		}

		w("\tVADD V12.S4, V14.S4, V12.S4   // F + (a+X+T)")

		// Rotate left: (x<<s) | (x>>(32-s))
		// NEON: VSHL + USHR + VORR (no native rotate for .4S)
		w("\tVSHL $%d, V12.S4, V11.S4   // left = x << s", s)
		w("\tUSHR $%d, V12.S4, V12.S4   // right = (uint32)x >> (32-s)", 32-s)
		w("\tVORR V11.B16, V12.B16, V12.B16  // rotl")

		// a = b + rotl_result
		w("\tVADD %s.S4, V12.S4, %s.S4", rB, rA)
		w("")
	}

	// Add back initial state
	w("\tVADD V4.S4, V0.S4, V0.S4")
	w("\tVADD V5.S4, V1.S4, V1.S4")
	w("\tVADD V6.S4, V2.S4, V2.S4")
	w("\tVADD V7.S4, V3.S4, V3.S4")
	w("")
	// Store state
	w("\tVST1 [V0.4S, V1.4S, V2.4S, V3.4S], 0(R1)")
	w("\tRET")
	w("")

	// Data tables
	w("DATA allones<>+0(SB)/8,  $0xFFFFFFFFFFFFFFFF")
	w("DATA allones<>+8(SB)/8,  $0xFFFFFFFFFFFFFFFF")
	w("GLOBL allones<>(SB), RODATA|NOPTR, $16")
	w("")

	for i, t := range T {
		w("DATA T_%d<>+0(SB)/4, $0x%08x", i, t)
		w("DATA T_%d<>+4(SB)/4, $0x%08x", i, t)
		w("DATA T_%d<>+8(SB)/4, $0x%08x", i, t)
		w("DATA T_%d<>+12(SB)/4, $0x%08x", i, t)
		w("GLOBL T_%d<>(SB), RODATA|NOPTR, $16", i)
		w("")
	}
}
