// Code generator for 4-way MD5 ARM64 NEON.
// Produces md5x4_neon.S — GNU assembler syntax for aarch64-linux-gnu-as.
//
// Workflow to get WORD encodings for Go asm:
//   aarch64-linux-gnu-as -o md5x4_neon.o md5x4_neon.S
//   aarch64-linux-gnu-objdump -d md5x4_neon.o
//   → plug WORD hex values into md5x4_arm64.s
//
// Usage: cd gen_md5x4 && go run .
package main

import (
	"fmt"
	"os"
)

func main() {
	f, err := os.Create("../md5x4_neon.S")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	w := func(s string, args ...interface{}) {
		fmt.Fprintf(f, s+"\n", args...)
	}

	w("// Generated by gen_md5x4 — GNU assembler syntax for aarch64-linux-gnu-as")
	w("// 4-way MD5 NEON core: 64 unrolled steps with register rotation")
	w("//")
	w("// Assemble:  aarch64-linux-gnu-as -o md5x4_neon.o md5x4_neon.S")
	w("// Disassemble: aarch64-linux-gnu-objdump -d md5x4_neon.o")
	w("// Goal: extract WORD hex values for Go Plan 9 asm (md5x4_arm64.s)")
	w("")
	w("\t.arch armv8-a")
	w("\t.text")
	w("\t.globl md5x4core")
	w("\t.type md5x4core, @function")
	w("md5x4core:")
	w("\t// x0 = &x (16 transposed message words, 16×16=256 bytes)")
	w("\t// x1 = &state ([4][4]uint32, a,b,c,d for 4 lanes)")
	w("")
	w("\t// Load state into v0-v3")
	w("\tld1 {v0.4s, v1.4s, v2.4s, v3.4s}, [x1]")
	w("")
	w("\t// Save initial state for final add-back: v4-v7")
	w("\tmov v4.16b, v0.16b")
	w("\tmov v5.16b, v1.16b")
	w("\tmov v6.16b, v2.16b")
	w("\tmov v7.16b, v3.16b")
	w("")

	T := [64]uint32{
		0xd76aa478, 0xe8c7b756, 0x242070db, 0xc1bdceee,
		0xf57c0faf, 0x4787c62a, 0xa8304613, 0xfd469501,
		0x698098d8, 0x8b44f7af, 0xffff5bb1, 0x895cd7be,
		0x6b901122, 0xfd987193, 0xa679438e, 0x49b40821,
		0xf61e2562, 0xc040b340, 0x265e5a51, 0xe9b6c7aa,
		0xd62f105d, 0x02441453, 0xd8a1e681, 0xe7d3fbc8,
		0x21e1cde6, 0xc33707d6, 0xf4d50d87, 0x455a14ed,
		0xa9e3e905, 0xfcefa3f8, 0x676f02d9, 0x8d2a4c8a,
		0xfffa3942, 0x8771f681, 0x6d9d6122, 0xfde5380c,
		0xa4beea44, 0x4bdecfa9, 0xf6bb4b60, 0xbebfbc70,
		0x289b7ec6, 0xeaa127fa, 0xd4ef3085, 0x04881d05,
		0xd9d4d039, 0xe6db99e5, 0x1fa27cf8, 0xc4ac5665,
		0xf4292244, 0x432aff97, 0xab9423a7, 0xfc93a039,
		0x655b59c3, 0x8f0ccc92, 0xffeff47d, 0x85845dd1,
		0x6fa87e4f, 0xfe2ce6e0, 0xa3014314, 0x4e0811a1,
		0xf7537e82, 0xbd3af235, 0x2ad7d2bb, 0xeb86d391,
	}

	shifts := [64]int{}
	gVals := [64]int{}
	for i := 0; i < 64; i++ {
		switch {
		case i < 16:
			gVals[i] = i
			shifts[i] = []int{7, 12, 17, 22}[i%4]
		case i < 32:
			gVals[i] = (5*i + 1) % 16
			shifts[i] = []int{5, 9, 14, 20}[i%4]
		case i < 48:
			gVals[i] = (3*i + 5) % 16
			shifts[i] = []int{4, 11, 16, 23}[i%4]
		default:
			gVals[i] = (7 * i) % 16
			shifts[i] = []int{6, 10, 15, 21}[i%4]
		}
	}

	// Register rotation: logical (a,b,c,d) → physical v0-v3
	perm := [4][4]int{
		{0, 1, 2, 3}, // i%4==0: a=v0, b=v1, c=v2, d=v3
		{3, 0, 1, 2}, // i%4==1: a=v3, b=v0, c=v1, d=v2
		{2, 3, 0, 1}, // i%4==2: a=v2, b=v3, c=v0, d=v1
		{1, 2, 3, 0}, // i%4==3: a=v1, b=v2, c=v3, d=v0
	}

	vreg := func(idx int) string { return fmt.Sprintf("v%d.4s", idx) }

	// Preload X[0] into v13
	w("\tldr q13, [x0, #%d]\t\t// X[0]", gVals[0]*16)
	w("")

	for i := 0; i < 64; i++ {
		g := gVals[i]
		s := shifts[i]
		round := i / 16

		p := perm[i%4]
		ra := vreg(p[0])
		rb := vreg(p[1])
		rc := vreg(p[2])
		rd := vreg(p[3])

		w("\t// Step %d: R%d g=%d s=%d T=0x%08x (a=v%d b=v%d c=v%d d=v%d)",
			i, round+1, g, s, T[i], p[0], p[1], p[2], p[3])

		// Round function
		switch round {
		case 0: // F = (b&c) | (~b&d)
			w("\tand v9.16b, %s, %s", rb, rc)
			w("\tbic v10.4s, %s, %s", rd, rb)
			w("\torr v12.16b, v9.16b, v10.16b")
		case 1: // F = (b&d) | (c&~d)
			w("\tand v9.16b, %s, %s", rb, rd)
			w("\tbic v10.4s, %s, %s", rc, rd)
			w("\torr v12.16b, v9.16b, v10.16b")
		case 2: // F = b ^ c ^ d
			w("\teor v12.16b, %s, %s", rb, rc)
			w("\teor v12.16b, v12.16b, %s", rd)
		case 3: // F = c ^ (b | ~d)
			w("\torn v9.16b, %s, %s", rb, rd)
			w("\teor v12.16b, %s, v9.16b", rc)
		}

		// a + X + T (T constant loaded via mov+movk+dup)
		w("\tadd v14.4s, %s, v13.4s", ra)
		w("\tmov w2, #0x%04x", T[i]&0xFFFF)
		w("\tmovk w2, #0x%04x, lsl #16", (T[i]>>16)&0xFFFF)
		w("\tdup v15.4s, w2")
		w("\tadd v14.4s, v14.4s, v15.4s")

		// Prefetch next X
		if i < 63 {
			w("\tldr q13, [x0, #%d]\t\t// X[%d]", gVals[i+1]*16, gVals[i+1])
		}

		w("\tadd v12.4s, v12.4s, v14.4s")
		w("\tshl v11.4s, v12.4s, #%d", s)
		w("\tushr v12.4s, v12.4s, #%d", 32-s)
		w("\torr v12.16b, v11.16b, v12.16b")
		w("\tadd %s, %s, v12.4s", ra, rb)
		w("")
	}

	// After 64 steps, perm returns to identity: v0=a, v1=b, v2=c, v3=d
	// Add back initial state and store
	w("\t// Final add-back")
	w("\tadd v0.4s, v0.4s, v4.4s")
	w("\tadd v1.4s, v1.4s, v5.4s")
	w("\tadd v2.4s, v2.4s, v6.4s")
	w("\tadd v3.4s, v3.4s, v7.4s")
	w("")
	w("\tst1 {v0.4s, v1.4s, v2.4s, v3.4s}, [x1]")
	w("\tret")
}
