// Code generator for 4-way MD5 ARM64 NEON.
// Produces md5x4_arm64.s using ONLY native Go ARM64 assembler mnemonics.
// No WORD encodings needed — VBIC/VORN emulated via VEOR(allones)+VAND/VORR.
//
// Usage: cd gen_md5x4 && go run .
package main

import (
	"fmt"
	"os"
)

func main() {
	f, err := os.Create("../md5x4_arm64.s")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	w := func(s string, args ...interface{}) {
		fmt.Fprintf(f, s+"\n", args...)
	}

	w("// Code generated by gen_md5x4; DO NOT EDIT.")
	w("// 4-way MD5 ARM64 NEON — 64 unrolled steps with implicit register rotation.")
	w("// Uses only native Go ARM64 assembler mnemonics (no WORD encodings).")
	w("// VBIC/VORN emulated via VEOR(allones) + VAND/VORR.")
	w("")
	w("#include \"textflag.h\"")
	w("")
	w("// func md5x4core(x *[16][4]uint32, state *[4][4]uint32)")
	w("TEXT ·md5x4core(SB), NOSPLIT, $0-16")
	w("\tMOVD x+0(FP), R0")
	w("\tMOVD state+8(FP), R1")
	w("")
	// State: V0=a, V1=b, V2=c, V3=d (roles rotate per step)
	// Saved: V4=sa, V5=sb, V6=sc, V7=sd
	// Work:  V9,V10=F temps, V11=rotl left, V12=F|rotl, V13=X[g], V14=accum, V15=T
	w("\tVLD1 0(R1), [V0.S4, V1.S4, V2.S4, V3.S4]")
	w("")
	w("\t// Save initial state for final add-back")
	w("\tVMOV V0.B16, V4.B16")
	w("\tVMOV V1.B16, V5.B16")
	w("\tVMOV V2.B16, V6.B16")
	w("\tVMOV V3.B16, V7.B16")
	w("")

	T := [64]uint32{
		0xd76aa478, 0xe8c7b756, 0x242070db, 0xc1bdceee,
		0xf57c0faf, 0x4787c62a, 0xa8304613, 0xfd469501,
		0x698098d8, 0x8b44f7af, 0xffff5bb1, 0x895cd7be,
		0x6b901122, 0xfd987193, 0xa679438e, 0x49b40821,
		0xf61e2562, 0xc040b340, 0x265e5a51, 0xe9b6c7aa,
		0xd62f105d, 0x02441453, 0xd8a1e681, 0xe7d3fbc8,
		0x21e1cde6, 0xc33707d6, 0xf4d50d87, 0x455a14ed,
		0xa9e3e905, 0xfcefa3f8, 0x676f02d9, 0x8d2a4c8a,
		0xfffa3942, 0x8771f681, 0x6d9d6122, 0xfde5380c,
		0xa4beea44, 0x4bdecfa9, 0xf6bb4b60, 0xbebfbc70,
		0x289b7ec6, 0xeaa127fa, 0xd4ef3085, 0x04881d05,
		0xd9d4d039, 0xe6db99e5, 0x1fa27cf8, 0xc4ac5665,
		0xf4292244, 0x432aff97, 0xab9423a7, 0xfc93a039,
		0x655b59c3, 0x8f0ccc92, 0xffeff47d, 0x85845dd1,
		0x6fa87e4f, 0xfe2ce6e0, 0xa3014314, 0x4e0811a1,
		0xf7537e82, 0xbd3af235, 0x2ad7d2bb, 0xeb86d391,
	}

	gVals := [64]int{}
	shifts := [64]int{}
	for i := 0; i < 64; i++ {
		switch {
		case i < 16:
			gVals[i] = i
			shifts[i] = []int{7, 12, 17, 22}[i%4]
		case i < 32:
			gVals[i] = (5*i + 1) % 16
			shifts[i] = []int{5, 9, 14, 20}[i%4]
		case i < 48:
			gVals[i] = (3*i + 5) % 16
			shifts[i] = []int{4, 11, 16, 23}[i%4]
		default:
			gVals[i] = (7 * i) % 16
			shifts[i] = []int{6, 10, 15, 21}[i%4]
		}
	}

	perm := [4][4]int{
		{0, 1, 2, 3}, // i%4==0: a=V0, b=V1, c=V2, d=V3
		{3, 0, 1, 2}, // i%4==1: a=V3, b=V0, c=V1, d=V2
		{2, 3, 0, 1}, // i%4==2: a=V2, b=V3, c=V0, d=V1
		{1, 2, 3, 0}, // i%4==3: a=V1, b=V2, c=V3, d=V0
	}

	vreg := func(idx int) string { return fmt.Sprintf("V%d", idx) }

	// Preload X[0]
	w("\tADD $%d, R0, R4", gVals[0]*16)
	w("\tVLD1 (R4), [V13.S4]")
	w("")

	for i := 0; i < 64; i++ {
		g := gVals[i]
		s := shifts[i]
		rnd := i / 16

		p := perm[i%4]
		ra := vreg(p[0])
		rb := vreg(p[1])
		rc := vreg(p[2])
		rd := vreg(p[3])

		w("\t// Step %d: R%d g=%d s=%d T=0x%08x  (a=%s b=%s c=%s d=%s)",
			i, rnd+1, g, s, T[i], ra, rb, rc, rd)

		// WORD encoding helpers: use p[0..3] (physical V0..V3 indexes)
		bicWord := func(rd, rn, rm int) string {
			return fmt.Sprintf("$0x%08x", 0x4E601C00|(rm<<16)|(rn<<5)|rd)
		}
		ornWord := func(rd, rn, rm int) string {
			return fmt.Sprintf("$0x%08x", 0x4EE01C00|(rm<<16)|(rn<<5)|rd)
		}

		physB := p[1] // physical register for b
		physC := p[2] // physical register for c
		physD := p[3] // physical register for d

		switch rnd {
		case 0: // F = (b&c) | (~b&d) = (b&c) | (d&~b)
			w("\tVAND %s.B16, %s.B16, V9.B16   // b & c", rb, rc)
			w("\tWORD %s                  // V10 = d & ~b (VBIC)", bicWord(10, physD, physB))
			w("\tVORR V9.B16, V10.B16, V12.B16  // F")
		case 1: // F = (b&d) | (c&~d)
			w("\tVAND %s.B16, %s.B16, V9.B16   // b & d", rb, rd)
			w("\tWORD %s                  // V10 = c & ~d (VBIC)", bicWord(10, physC, physD))
			w("\tVORR V9.B16, V10.B16, V12.B16  // F")
		case 2: // F = b ^ c ^ d
			w("\tVEOR %s.B16, %s.B16, V12.B16", rb, rc)
			w("\tVEOR %s.B16, V12.B16, V12.B16", rd)
		case 3: // F = c ^ (b | ~d)
			w("\tWORD %s                  // V9 = b | ~d (VORN)", ornWord(9, physB, physD))
			w("\tVEOR %s.B16, V9.B16, V12.B16  // F = c ^ (b|~d)", rc)
		}

		// a + X + T
		w("\tVADD %s.S4, V13.S4, V14.S4   // a + X", ra)
		w("\tMOVD $T_%d<>(SB), R3", i)
		w("\tVLD1 (R3), [V15.S4]")
		w("\tVADD V15.S4, V14.S4, V14.S4  // a + X + T")

		// Prefetch next X
		if i < 63 {
			w("\tADD $%d, R0, R4", gVals[i+1]*16)
			w("\tVLD1 (R4), [V13.S4]")
		}

		w("\tVADD V12.S4, V14.S4, V12.S4  // F + (a+X+T)")

		// Rotate: VSHL + VUSHR + VORR
		w("\tVSHL $%d, V12.S4, V11.S4   // x << s", s)
		w("\tVUSHR $%d, V12.S4, V12.S4  // x >> (32-s)", 32-s)
		w("\tVORR V11.B16, V12.B16, V12.B16  // rotl")

		// a = b + rotl
		w("\tVADD %s.S4, V12.S4, %s.S4", rb, ra)
		w("")
	}

	w("\t// Final add-back")
	w("\tVADD V4.S4, V0.S4, V0.S4")
	w("\tVADD V5.S4, V1.S4, V1.S4")
	w("\tVADD V6.S4, V2.S4, V2.S4")
	w("\tVADD V7.S4, V3.S4, V3.S4")
	w("")
	w("\tVST1 [V0.S4, V1.S4, V2.S4, V3.S4], 0(R1)")
	w("\tRET")
	w("")

	for i, t := range T {
		w("DATA T_%d<>+0(SB)/4, $0x%08x", i, t)
		w("DATA T_%d<>+4(SB)/4, $0x%08x", i, t)
		w("DATA T_%d<>+8(SB)/4, $0x%08x", i, t)
		w("DATA T_%d<>+12(SB)/4, $0x%08x", i, t)
		w("GLOBL T_%d<>(SB), RODATA|NOPTR, $16", i)
		w("")
	}
}
